import "@radix-ui/themes/styles.css";

import { ThemeProvider } from "@/components/theme-provider";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./theme-config.css";
import "./globals.css";

import { Theme } from "@radix-ui/themes";

import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <ThemeProvider attribute="class">
          <Theme accentColor="violet" radius="large">
            <Navbar />
            <main className="p-5">{children}</main>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
